tunnel: <tunnel ID>
credentials-file: /root/.cloudflared/<tunnel ID>.json

ingress:
 - hostname: test.example.com
   service: http://127.0.0.1:6900
 - hostname: ssh.example.com
   service: ssh://localhost:22
 - service: http_status:404
